"""Emit C headers from protocol TypeDef records so GDB can ingest structs."""

from __future__ import annotations

from .types import TypeDef


def types_to_c_header(types: list[TypeDef]) -> str:
    lines = [
        "/* Generated by Ariadne — include from GDB or compile with -g */",
        "#pragma once",
        "",
    ]
    for typedef in types:
        if typedef.struct is None:
            if typedef.text:
                lines.append(f"/* {typedef.name}: {typedef.kind} */")
                lines.append(f"{typedef.text};")
                lines.append("")
            continue
        struct = typedef.struct
        lines.append(f"struct {struct.name} {{")
        cursor = 0
        pad = 0
        for member in sorted(struct.members, key=lambda m: m.offset):
            if member.offset > cursor:
                gap = member.offset - cursor
                lines.append(f"    char __bn_pad_{pad}[{gap}];")
                pad += 1
                cursor = member.offset
            ctype = c_type(member.type_name)
            lines.append(f"    {ctype} {member.name};")
            cursor = member.offset + (member.size or 0)
        if struct.size and cursor < struct.size:
            lines.append(f"    char __bn_tail[{struct.size - cursor}];")
        lines.append("};")
        lines.append("")
    return "\n".join(lines)


def c_type(type_name: str) -> str:
    raw = (type_name or "char").strip()
    aliases = {
        "int8_t": "int8_t",
        "uint8_t": "uint8_t",
        "int16_t": "int16_t",
        "uint16_t": "uint16_t",
        "int32_t": "int32_t",
        "uint32_t": "uint32_t",
        "int64_t": "int64_t",
        "uint64_t": "uint64_t",
        "char": "char",
        "int": "int",
        "void*": "void*",
    }
    if raw in aliases:
        return aliases[raw]
    return raw.replace("::", "_")
